### ISSUE TITLE
Small fix

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaCN/Py2Jl.jl#10]
I added https://github.com/PallHaraldsson/Py2Jl.jl/commit/4d6e673463f3c7218973ae57d96d169d53c94619 after you merged PR.

Can you merge this, or do you need another PR? I'm not sure how/if you or I can convert a commit to a PR or have to do manually?

**Comment by thautwarm** [comment]
Done.

**Comment by thautwarm** [comment]
I'm going to sleep now. If problems just make a issue.
Thanks for your contributions! Once I'm not that busy, I'll send an application to grant the write permission of this repo for you.
